import Head from 'next/head'
import { useState } from 'react'
import Link from 'next/link';

export default function Home() {

  const [land, setLand] = useState('');

  // Function to handle input change
  const handleInputChange = (e) => {
    setLand(e.target.value);
  };

  // Function to clear the land ID input
  const handleClear = () => {
    setLand('');
  };

  return (
    <div className="flex justify-center items-center h-screen">
      <Head>
        <title>Pixels Tools</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-center">
        <h1 className="font-bold text-3xl mb-4">Pixels Tools</h1>
        <h2 className="font-semibold text-xl mb-4">Land Finder</h2>
        <div className='max-w-sm'>
        <p>Watch your land using this tools, live time updates, automatically opens new tab for you, you can watch more than 2 lands just enter ur land id and click view</p>
        </div>   
        <input
          type="text"
          value={land}
          onChange={handleInputChange}
          placeholder="Enter land ID (number)"
          className="border border-gray-300 rounded-md px-4 py-2 mb-4 mr-2"
        />
        <button
          onClick={handleClear}
          className="bg-red-500 text-white px-4 py-2 rounded-md"
        >
          Clear
        </button>
        <Link href={`https://play.pixels.xyz/pixels/share/${land}`} target="_blank">
          <p className="bg-blue-500 text-white px-4 py-2 rounded-md ml-2">View</p>
        </Link>
        <Link href="https://play.pixels.xyz/" target="_blank">
          <p className="bg-blue-500 text-white px-4 py-2 rounded-md ml-2 mt-2">Play Pixels</p>
        </Link>
        <Link href="https://t.me/koperasipetani" target="_blank">
          <p className="bg-blue-500 text-white px-4 py-2 rounded-md ml-2 mt-2">Telegram</p>
        </Link>
      </div>
    </div>
  )
}
